spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7