spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# Enable all metric for actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
# detailed health information
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  # Indormation endpoint from actuator
  info:
    env:
      enabled: true

server:
  shutdown: graceful

# injecting custom application information
info:
  app:
    name: E-Commerce Application
    description: A sample e-commerce application with microservices architecture
    version: 1.0.0