spring:
  datasource:
    #    For local PostgreSQL database, use the following configuration: docer-compose.yml
    url: jdbc:postgresql://localhost:5432/order
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  rabbitmq: # For RabbitMQ configuration
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  message: "HELLO from order-service"