spring:
  application:
    name: configserver
  profiles:
    active: native
  rabbitmq: # For RabbitMQ configuration
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:////Users/martinbaliak/Documents/Projects-learning/ecom-microservices/configserver/src/main/resources/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'